reload:
  message:
    - "&e&lReloaded RandomBlock Plugin "
    - "&d&lHave an Epic Time"

#--------------------------------------------------------------------------------------------------------------------------------------
#
#
#░██╗░░░░░░░██╗░█████╗░██████╗░██╗░░░░░██████╗░        ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░
#░██║░░██╗░░██║██╔══██╗██╔══██╗██║░░░░░██╔══██╗        ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░
#░╚██╗████╗██╔╝██║░░██║██████╔╝██║░░░░░██║░░██║        ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░
#░░████╔═████║░██║░░██║██╔══██╗██║░░░░░██║░░██║        ██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗
#░░╚██╔╝░╚██╔╝░╚█████╔╝██║░░██║███████╗██████╔╝        ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝
#░░░╚═╝░░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░        ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░
#
#
#--------------------------------------------------------------------------------------------------------------------------------------

#Here select the Worlds for this plugin to apply to, only worlds listed here will be able to use this plugin

#you can if you want to add "" around the world name if the plugin isn't working for a world..

#WARNING. THIS IS CASE SENSITIVE. please make sure its the exact same name with the correct capitalization

# ignoreSelector.ALL ignores the world filter so taht all worlds will use the plugin

#BE SURE TO ADD YOUR WORLDS HERE PLEASE.
worlds:
  - "world1"
  - World2
  #- ignoreSelector.ALL

#--------------------------------------------------------------------------------------------------------------------------------------
#
#
#
#  ██████╗░██╗░░░░░░█████╗░░█████╗░██╗░░██╗        ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░
#  ██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░██╔╝        ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░
#  ██████╦╝██║░░░░░██║░░██║██║░░╚═╝█████═╝░        ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░
#  ██╔══██╗██║░░░░░██║░░██║██║░░██╗██╔═██╗░        ██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗
#  ██████╦╝███████╗╚█████╔╝╚█████╔╝██║░╚██╗        ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝
#  ╚═════╝░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝        ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░
#
#--------------------------------------------------------------------------------------------------------------------------------------

#Add a block to make it random, and select the blocks it "could" drop instead of the actual block

#During the tests, i get confused on why its not working, but it is, make sure your mining DIRT not GRASS

#BLOCK CONFIG EXAMPLE

blocks:
  DIRT:
    - STONE
    - DIRT
    - DIRT
    - DIRT
    - GRASS_BLOCK
    - AIR
    - DIRT
    - STONE
    - COBBLESTONE
    - COBBLESTONE
    - COBBLESTONE
    - AIR
    - AIR
    - DIRT

  #This is for 1 drop, its the same, but don't add another thing, and done.
  GRASS_BLOCK:
    - GRASS_BLOCK

#--------------------------------------------------------------------------------------------------------------------------------------
#
#
#░█████╗░███╗░░░███╗░█████╗░██╗░░░██╗███╗░░██╗████████╗      ██████╗░██████╗░░█████╗░██████╗░
#██╔══██╗████╗░████║██╔══██╗██║░░░██║████╗░██║╚══██╔══╝      ██╔══██╗██╔══██╗██╔══██╗██╔══██╗
#███████║██╔████╔██║██║░░██║██║░░░██║██╔██╗██║░░░██║         ██║░░██║██████╔╝██║░░██║██████╔╝
#██╔══██║██║╚██╔╝██║██║░░██║██║░░░██║██║╚████║░░░██║         ██║░░██║██╔══██╗██║░░██║██╔═══╝░
#██║░░██║██║░╚═╝░██║╚█████╔╝╚██████╔╝██║░╚███║░░░██║         ██████╔╝██║░░██║╚█████╔╝██║░░░░░
#╚═╝░░╚═╝╚═╝░░░░░╚═╝░╚════╝░░╚═════╝░╚═╝░░╚══╝░░░╚═╝         ╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░
#
#--------------------------------------------------------------------------------------------------------------------------------------

#the amount it should drop, put it to FALSE, for random drops between 1-your-choice
drop-amount: FALSE

#THIS ONLY WORKS WHEN drop-amount is FALSE

#the max amount the blocks can drop | From MIN-NUMBER-MAX-NUMBER
Max-drop-amount: 4
Min-drop-amount: 2
